# Setup
title:               IG
tagline:             Izzy Gomez
url:                 https://izzygomez.com

# About/contact
author:
  name:              Izzy Gomez
  url:               https://izzygomez.com
  email:             izzygmit@gmail.com
