# Setup
title:               Izzy Gomez
tagline:             yo
url:                 https://izzygomez.com

# About/contact
author:
  name:              Izzy Gomez
  url:               https://izzygomez.com
  email:             izzygmit@gmail.com
