# Setup
title:               Izzy Gomez
tagline:             yo
url:                 https://izzy.gg

# About/contact
author:
  name:              Izzy Gomez
  url:               https://izzy.gg
  email:             izzygmit@gmail.com
