# Config (https://jekyllrb.com/docs/step-by-step/09-collections/#configuration)
title: Izzy Gomez
url: https://izzygomez.com
email: izzy@izzygomez.com

exclude: ["*README.md"]

# Custom collections folder to not have root directory too cluttered
# https://jekyllrb.com/docs/collections/
collections_dir: collections
