# Site settings
title: The Site of Izzy Gomez
email: izzyg@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the description to my website. I hope I've been entertaining and
  you've learned a thing or two. -Izzy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: gomizzy
github_username:  izzygomez

# Build settings
markdown: kramdown
